### Variable Standardization ###

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import statistics as stats

In [12]:
df=sns.load_dataset('diamonds')
df.head(5)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [16]:
dff=df.select_dtypes(include=['float64', 'int64'])
dff

carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 7 columns]

#### Standardization ####

In [14]:
from sklearn import preprocessing

In [17]:
preprocessing.scale(dff)

array([[-1.19816781, -0.17409151, -1.09967199, ..., -1.58783745,
        -1.53619556, -1.57112919],
       [-1.24036129, -1.36073849,  1.58552871, ..., -1.64132529,
        -1.65877419, -1.74117497],
       [-1.19816781, -3.38501862,  3.37566251, ..., -1.49869105,
        -1.45739502, -1.74117497],
       ...,
       [-0.20662095,  0.73334442,  1.13799526, ..., -0.06343409,
        -0.04774083,  0.03013526],
       [ 0.13092691, -0.52310533,  0.24292836, ...,  0.37338325,
         0.33750627,  0.28520393],
       [-0.10113725,  0.31452784, -1.09967199, ...,  0.08811478,
         0.11861587,  0.14349912]])

#### Normalization ####

In [19]:
preprocessing.normalize(dff)

array([[0.00068384, 0.18285388, 0.16352786, ..., 0.01174427, 0.01183347,
        0.00722496],
       [0.00062304, 0.17741738, 0.18097759, ..., 0.01154103, 0.01139269,
        0.00685341],
       [0.00067992, 0.16820635, 0.19215136, ..., 0.01197251, 0.01203163,
        0.00682876],
       ...,
       [0.00025377, 0.02276697, 0.02175188, ..., 0.00205193, 0.00205918,
        0.00129061],
       [0.00031179, 0.02211506, 0.02102744, ..., 0.00222963, 0.00221876,
        0.00135591],
       [0.00027191, 0.02255041, 0.01994007, ..., 0.00211365, 0.00212815,
        0.00131967]])

#### Transformations-(MinMaxScaler) ####

In [23]:
a=preprocessing.MinMaxScaler(feature_range=(10,20))

In [24]:
a.fit_transform(dff)

array([[10.06237006, 15.13888889, 12.30769231, ..., 13.67783985,
        10.67572156, 10.76415094],
       [10.02079002, 14.66666667, 13.46153846, ..., 13.62197393,
        10.65195246, 10.72641509],
       [10.06237006, 13.86111111, 14.23076923, ..., 13.77094972,
        10.6910017 , 10.72641509],
       ...,
       [11.03950104, 15.5       , 13.26923077, ..., 15.27001862,
        10.96434635, 11.11949686],
       [11.37214137, 15.        , 12.88461538, ..., 15.72625698,
        11.03904924, 11.17610063],
       [11.14345114, 15.33333333, 12.30769231, ..., 15.4283054 ,
        10.99660441, 11.14465409]])

In [25]:
b=preprocessing.MinMaxScaler(feature_range=(1000,2500))

In [26]:
b.fit_transform(dff)

array([[1009.35550936, 1770.83333333, 1346.15384615, ..., 1551.67597765,
        1101.3582343 , 1114.62264151],
       [1003.11850312, 1700.        , 1519.23076923, ..., 1543.29608939,
        1097.79286927, 1108.96226415],
       [1009.35550936, 1579.16666667, 1634.61538462, ..., 1565.6424581 ,
        1103.65025467, 1108.96226415],
       ...,
       [1155.92515593, 1825.        , 1490.38461538, ..., 1790.5027933 ,
        1144.65195246, 1167.9245283 ],
       [1205.82120582, 1750.        , 1432.69230769, ..., 1858.93854749,
        1155.8573854 , 1176.41509434],
       [1171.51767152, 1800.        , 1346.15384615, ..., 1814.24581006,
        1149.49066214, 1171.69811321]])

#### 0-1 Transformation ####

In [28]:
tip=sns.load_dataset('tips')
tip

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [29]:
tip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.3 KB


In [30]:
from sklearn.preprocessing import LabelEncoder

In [39]:
tip['sex']=LabelEncoder().fit_transform(tip['sex'])
tip

total_bill   tip  sex smoker   day    time  size
0         16.99  1.01    0     No   Sun  Dinner     2
1         10.34  1.66    1     No   Sun  Dinner     3
2         21.01  3.50    1     No   Sun  Dinner     3
3         23.68  3.31    1     No   Sun  Dinner     2
4         24.59  3.61    0     No   Sun  Dinner     4
..          ...   ...  ...    ...   ...     ...   ...
239       29.03  5.92    1     No   Sat  Dinner     3
240       27.18  2.00    0    Yes   Sat  Dinner     2
241       22.67  2.00    1    Yes   Sat  Dinner     2
242       17.82  1.75    1     No   Sat  Dinner     2
243       18.78  3.00    0     No  Thur  Dinner     2

[244 rows x 7 columns]

In [35]:
LabelEncoder().fit_transform(tip['smoker'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0])

In [46]:
tip['smoker']=LabelEncoder().fit_transform(tip['smoker'])
tip

total_bill   tip  sex  smoker   day    time  size
0         16.99  1.01    0       0   Sun  Dinner     2
1         10.34  1.66    1       0   Sun  Dinner     3
2         21.01  3.50    1       0   Sun  Dinner     3
3         23.68  3.31    1       0   Sun  Dinner     2
4         24.59  3.61    0       0   Sun  Dinner     4
..          ...   ...  ...     ...   ...     ...   ...
239       29.03  5.92    1       0   Sat  Dinner     3
240       27.18  2.00    0       1   Sat  Dinner     2
241       22.67  2.00    1       1   Sat  Dinner     2
242       17.82  1.75    1       0   Sat  Dinner     2
243       18.78  3.00    0       0  Thur  Dinner     2

[244 rows x 7 columns]

In [53]:
#tip['time']=np.where(tip['time'].str.contains('Dinner'),1,0)

You should review that 'Dinner' is one.

In [52]:
tip

total_bill   tip  sex  smoker   day  time  size
0         16.99  1.01    0       0   Sun     1     2
1         10.34  1.66    1       0   Sun     1     3
2         21.01  3.50    1       0   Sun     1     3
3         23.68  3.31    1       0   Sun     1     2
4         24.59  3.61    0       0   Sun     1     4
..          ...   ...  ...     ...   ...   ...   ...
239       29.03  5.92    1       0   Sat     1     3
240       27.18  2.00    0       1   Sat     1     2
241       22.67  2.00    1       1   Sat     1     2
242       17.82  1.75    1       0   Sat     1     2
243       18.78  3.00    0       0  Thur     1     2

[244 rows x 7 columns]

In [54]:
tip['day']=np.where(tip['day'].str.contains('Sat'),1,0)
tip

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    0     1     2
1         10.34  1.66    1       0    0     1     3
2         21.01  3.50    1       0    0     1     3
3         23.68  3.31    1       0    0     1     2
4         24.59  3.61    0       0    0     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    0     1     2

[244 rows x 7 columns]

You should use 'One-hot Transformation' ,if any columns contain more two unique value.Because '1-0 Transformation' lead to bias.

In [56]:
df_1=sns.load_dataset('diamonds')
df_1

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [57]:
df_1=pd.get_dummies(df_1, columns=['cut'], prefix=['day'])

In [58]:
df_1

carat color clarity  depth  table  price     x     y     z  day_Ideal  \
0       0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43          1   
1       0.21     E     SI1   59.8   61.0    326  3.89  3.84  2.31          0   
2       0.23     E     VS1   56.9   65.0    327  4.05  4.07  2.31          0   
3       0.29     I     VS2   62.4   58.0    334  4.20  4.23  2.63          0   
4       0.31     J     SI2   63.3   58.0    335  4.34  4.35  2.75          0   
...      ...   ...     ...    ...    ...    ...   ...   ...   ...        ...   
53935   0.72     D     SI1   60.8   57.0   2757  5.75  5.76  3.50          1   
53936   0.72     D     SI1   63.1   55.0   2757  5.69  5.75  3.61          0   
53937   0.70     D     SI1   62.8   60.0   2757  5.66  5.68  3.56          0   
53938   0.86     H     SI2   61.0   58.0   2757  6.15  6.12  3.74          0   
53939   0.75     D     SI2   62.2   55.0   2757  5.83  5.87  3.64          1   

       day_Premium  day_Very Good  day_Good  day_Fair  
0                0              0         0         0  
1                1              0         0         0  
2                0              0         1         0  
3                1              0         0         0  
4                0              0         1         0  
...            ...            ...       ...       ...  
53935            0              0         0         0  
53936            0              0         1         0  
53937            0              1         0         0  
53938            1              0         0         0  
53939            0              0         0         0  

[53940 rows x 14 columns]

#### Data Standardization-Transformation ####

mean=0, std=1

In [59]:
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [65]:
df_n=df.select_dtypes(include=['float64','int64'])

In [66]:
preprocessing.scale(df_n)

array([[-1.19816781, -0.17409151, -1.09967199, ..., -1.58783745,
        -1.53619556, -1.57112919],
       [-1.24036129, -1.36073849,  1.58552871, ..., -1.64132529,
        -1.65877419, -1.74117497],
       [-1.19816781, -3.38501862,  3.37566251, ..., -1.49869105,
        -1.45739502, -1.74117497],
       ...,
       [-0.20662095,  0.73334442,  1.13799526, ..., -0.06343409,
        -0.04774083,  0.03013526],
       [ 0.13092691, -0.52310533,  0.24292836, ...,  0.37338325,
         0.33750627,  0.28520393],
       [-0.10113725,  0.31452784, -1.09967199, ...,  0.08811478,
         0.11861587,  0.14349912]])

#### Normalization ####

In [67]:
preprocessing.normalize(df_n)

array([[0.00068384, 0.18285388, 0.16352786, ..., 0.01174427, 0.01183347,
        0.00722496],
       [0.00062304, 0.17741738, 0.18097759, ..., 0.01154103, 0.01139269,
        0.00685341],
       [0.00067992, 0.16820635, 0.19215136, ..., 0.01197251, 0.01203163,
        0.00682876],
       ...,
       [0.00025377, 0.02276697, 0.02175188, ..., 0.00205193, 0.00205918,
        0.00129061],
       [0.00031179, 0.02211506, 0.02102744, ..., 0.00222963, 0.00221876,
        0.00135591],
       [0.00027191, 0.02255041, 0.01994007, ..., 0.00211365, 0.00212815,
        0.00131967]])

In [69]:
preprocessing.MinMaxScaler(feature_range=(5,6)).fit_transform(df_n)

array([[5.00623701, 5.51388889, 5.23076923, ..., 5.36778399, 5.06757216,
        5.07641509],
       [5.002079  , 5.46666667, 5.34615385, ..., 5.36219739, 5.06519525,
        5.07264151],
       [5.00623701, 5.38611111, 5.42307692, ..., 5.37709497, 5.06910017,
        5.07264151],
       ...,
       [5.1039501 , 5.55      , 5.32692308, ..., 5.52700186, 5.09643463,
        5.11194969],
       [5.13721414, 5.5       , 5.28846154, ..., 5.5726257 , 5.10390492,
        5.11761006],
       [5.11434511, 5.53333333, 5.23076923, ..., 5.54283054, 5.09966044,
        5.11446541]])

#### Binarize Transformation ####

In [76]:
a=preprocessing.Binarizer(threshold=5).fit(df_n)

In [77]:
a.transform(df_n)

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 0.]])

In [80]:
tips=sns.load_dataset('tips')
tips.head(4)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2

#### 0-1 Transformation ####

In [81]:
tips['smoker_y']=tips['smoker'].cat.codes

In [82]:
tips.head(5)

total_bill   tip     sex smoker  day    time  size  smoker_y
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         1

In [85]:
tips['smoker_yy']=preprocessing.LabelEncoder().fit_transform(tips['smoker'])
tips

total_bill   tip     sex smoker   day    time  size  smoker_y  smoker_yy
0         16.99  1.01  Female     No   Sun  Dinner     2         1          0
1         10.34  1.66    Male     No   Sun  Dinner     3         1          0
2         21.01  3.50    Male     No   Sun  Dinner     3         1          0
3         23.68  3.31    Male     No   Sun  Dinner     2         1          0
4         24.59  3.61  Female     No   Sun  Dinner     4         1          0
..          ...   ...     ...    ...   ...     ...   ...       ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0          1
242       17.82  1.75    Male     No   Sat  Dinner     2         1          0
243       18.78  3.00  Female     No  Thur  Dinner     2         1          0

[244 rows x 9 columns]

In [86]:
tips.head(5)

total_bill   tip     sex smoker  day    time  size  smoker_y  smoker_yy
0       16.99  1.01  Female     No  Sun  Dinner     2         1          0
1       10.34  1.66    Male     No  Sun  Dinner     3         1          0
2       21.01  3.50    Male     No  Sun  Dinner     3         1          0
3       23.68  3.31    Male     No  Sun  Dinner     2         1          0
4       24.59  3.61  Female     No  Sun  Dinner     4         1          0

In [87]:
tips['time']

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

Look at that 'Categories (2, object)'.

In [88]:
tips['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

Look at that 'Categories (4, object)'.

In [92]:
#tips['day_y']=np.where(['day'].str.contains('Sun'),1,0)

In [94]:
titanic=sns.load_dataset('titanic')
titanic.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [95]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [97]:
titanic['deck']

0      NaN
1        C
2      NaN
3        C
4      NaN
      ... 
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [98]:
titanic['deck_y']=preprocessing.LabelEncoder().fit_transform(titanic['deck'])

In [99]:
titanic.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  deck_y  
0    man        True  NaN  Southampton    no  False       7  
1  woman       False    C    Cherbourg   yes  False       2  
2  woman       False  NaN  Southampton   yes   True       7  
3  woman       False    C  Southampton   yes  False       2  
4    man        True  NaN  Southampton    no   True       7  
5    man        True  NaN   Queenstown    no   True       7  
6    man        True    E  Southampton    no   True       4  
7  child       False  NaN  Southampton    no  False       7  
8  woman       False  NaN  Southampton   yes  False       7  
9  child       False  NaN    Cherbourg   yes  False       7

In [102]:
tips

total_bill   tip     sex smoker   day    time  size  smoker_y  smoker_yy
0         16.99  1.01  Female     No   Sun  Dinner     2         1          0
1         10.34  1.66    Male     No   Sun  Dinner     3         1          0
2         21.01  3.50    Male     No   Sun  Dinner     3         1          0
3         23.68  3.31    Male     No   Sun  Dinner     2         1          0
4         24.59  3.61  Female     No   Sun  Dinner     4         1          0
..          ...   ...     ...    ...   ...     ...   ...       ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0          1
242       17.82  1.75    Male     No   Sat  Dinner     2         1          0
243       18.78  3.00  Female     No  Thur  Dinner     2         1          0

[244 rows x 9 columns]

In [107]:
pd.get_dummies(tips, columns=['smoker'], prefix=['smoker']).head(10)

total_bill   tip     sex  day    time  size  smoker_y  smoker_yy  \
0       16.99  1.01  Female  Sun  Dinner     2         1          0   
1       10.34  1.66    Male  Sun  Dinner     3         1          0   
2       21.01  3.50    Male  Sun  Dinner     3         1          0   
3       23.68  3.31    Male  Sun  Dinner     2         1          0   
4       24.59  3.61  Female  Sun  Dinner     4         1          0   
5       25.29  4.71    Male  Sun  Dinner     4         1          0   
6        8.77  2.00    Male  Sun  Dinner     2         1          0   
7       26.88  3.12    Male  Sun  Dinner     4         1          0   
8       15.04  1.96    Male  Sun  Dinner     2         1          0   
9       14.78  3.23    Male  Sun  Dinner     2         1          0   

   smoker_Yes  smoker_No  
0           0          1  
1           0          1  
2           0          1  
3           0          1  
4           0          1  
5           0          1  
6           0          1  
7           0          1  
8           0          1  
9           0          1

'One Hot' method should result in smaller than the number of unique values as attribute.

#### Transform from an index to variable or opposite ####

In [108]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  deck_y  
0      man        True  NaN  Southampton    no  False       7  
1    woman       False    C    Cherbourg   yes  False       2  
2    woman       False  NaN  Southampton   yes   True       7  
3    woman       False    C  Southampton   yes  False       2  
4      man        True  NaN  Southampton    no   True       7  
..     ...         ...  ...          ...   ...    ...     ...  
886    man        True  NaN  Southampton    no   True       7  
887  woman       False    B  Southampton   yes   True       1  
888  woman       False  NaN  Southampton    no  False       7  
889    man        True    C    Cherbourg   yes   True       2  
890    man        True  NaN   Queenstown    no   True       7  

[891 rows x 16 columns]

In [109]:
titanic['n_variable']=titanic.index

In [110]:
titanic.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  deck_y  n_variable  
0    man        True  NaN  Southampton    no  False       7           0  
1  woman       False    C    Cherbourg   yes  False       2           1  
2  woman       False  NaN  Southampton   yes   True       7           2  
3  woman       False    C  Southampton   yes  False       2           3  
4    man        True  NaN  Southampton    no   True       7           4

In [111]:
titanic['n_variable']=(titanic['n_variable']+20)/9

In [112]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  deck_y  n_variable  
0    man        True  NaN  Southampton    no  False       7    2.222222  
1  woman       False    C    Cherbourg   yes  False       2    2.333333  
2  woman       False  NaN  Southampton   yes   True       7    2.444444  
3  woman       False    C  Southampton   yes  False       2    2.555556  
4    man        True  NaN  Southampton    no   True       7    2.666667

In [114]:
titanic.index=titanic['n_variable']

In [115]:
titanic.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  \
n_variable                                                                   
2.222222           0       3    male  22.0      1      0   7.2500        S   
2.333333           1       1  female  38.0      1      0  71.2833        C   
2.444444           1       3  female  26.0      0      0   7.9250        S   
2.555556           1       1  female  35.0      1      0  53.1000        S   
2.666667           0       3    male  35.0      0      0   8.0500        S   

            class    who  adult_male deck  embark_town alive  alone  deck_y  \
n_variable                                                                    
2.222222    Third    man        True  NaN  Southampton    no  False       7   
2.333333    First  woman       False    C    Cherbourg   yes  False       2   
2.444444    Third  woman       False  NaN  Southampton   yes   True       7   
2.555556    First  woman       False    C  Southampton   yes  False       2   
2.666667    Third    man        True  NaN  Southampton    no   True       7   

            n_variable  
n_variable              
2.222222      2.222222  
2.333333      2.333333  
2.444444      2.444444  
2.555556      2.555556  
2.666667      2.666667

In [116]:
titanic.index

Float64Index([2.2222222222222223, 2.3333333333333335, 2.4444444444444446,
              2.5555555555555554, 2.6666666666666665, 2.7777777777777777,
               2.888888888888889,                3.0,  3.111111111111111,
              3.2222222222222223,
              ...
              100.11111111111111, 100.22222222222223, 100.33333333333333,
              100.44444444444444, 100.55555555555556, 100.66666666666667,
              100.77777777777777, 100.88888888888889,              101.0,
              101.11111111111111],
             dtype='float64', name='n_variable', length=891)

You review the names of indexes that it was described variable as index by us.